import { LegacyAlert as Alert, AlertThreshold } from "@/types/database"

export const SEED_ALERTS: Alert[] = [
  // Michigan (4 alerts)
  {
    id: 'alert-001',
    school_id: 'michigan',
    alert_type: 'sentiment-drop',
    severity: 'warning',
    title: 'Sentiment Score Below Threshold',
    message: 'Michigan\'s 7-day rolling sentiment score dropped below 0.3 following the Title IX complaint coverage. Current score: 0.28.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-003',
    is_read: false,
    is_emailed: true,
    created_at: '2026-03-30T08:00:00Z',
  },
  {
    id: 'alert-002',
    school_id: 'michigan',
    alert_type: 'ncaa-violation',
    severity: 'warning',
    title: 'NCAA Violation Reported',
    message: 'A minor NCAA recruiting violation was reported for men\'s basketball. Compliance team has been notified and self-report filed.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-004',
    is_read: true,
    is_emailed: true,
    created_at: '2026-03-15T11:30:00Z',
  },
  {
    id: 'alert-003',
    school_id: 'michigan',
    alert_type: 'coaching-change',
    severity: 'info',
    title: 'Coaching Change Detected',
    message: 'New women\'s volleyball head coach hire announced. Media coverage and social sentiment are being monitored.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-005',
    is_read: true,
    is_emailed: false,
    created_at: '2026-03-10T16:30:00Z',
  },
  {
    id: 'alert-004',
    school_id: 'michigan',
    alert_type: 'media-spike',
    severity: 'info',
    title: 'Media Mention Volume Spike',
    message: 'Michigan received 340% more media mentions than the 30-day average in the past 48 hours, driven by the booster influence investigation.',
    related_entity_type: null,
    related_entity_id: null,
    is_read: false,
    is_emailed: false,
    created_at: '2026-03-06T09:00:00Z',
  },

  // Alabama (4 alerts)
  {
    id: 'alert-005',
    school_id: 'alabama',
    alert_type: 'ncaa-violation',
    severity: 'critical',
    title: 'NCAA Inquiry Opened',
    message: 'The NCAA has opened a preliminary inquiry into Alabama football practice hour violations. Legal and compliance teams are coordinating a response.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-011',
    is_read: false,
    is_emailed: true,
    created_at: '2026-03-12T10:30:00Z',
  },
  {
    id: 'alert-006',
    school_id: 'alabama',
    alert_type: 'sentiment-drop',
    severity: 'warning',
    title: 'Social Sentiment Decline',
    message: 'Alabama\'s social media sentiment dropped 22% week-over-week due to ticket price backlash. Monitoring for further decline.',
    related_entity_type: null,
    related_entity_id: null,
    is_read: true,
    is_emailed: false,
    created_at: '2026-03-09T12:00:00Z',
  },
  {
    id: 'alert-007',
    school_id: 'alabama',
    alert_type: 'budget-threshold',
    severity: 'info',
    title: 'Budget Ratio Flag',
    message: 'Athletic spending as a percentage of total institutional budget has exceeded the 15% threshold at 16.2% for the current fiscal year.',
    related_entity_type: null,
    related_entity_id: null,
    is_read: true,
    is_emailed: false,
    created_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 'alert-008',
    school_id: 'alabama',
    alert_type: 'media-spike',
    severity: 'info',
    title: 'Positive Media Surge',
    message: 'Alabama gymnastics community outreach story picked up by 47 outlets in the past 24 hours. Sentiment is overwhelmingly positive.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-013',
    is_read: true,
    is_emailed: false,
    created_at: '2026-03-02T14:00:00Z',
  },

  // Oregon (4 alerts)
  {
    id: 'alert-009',
    school_id: 'oregon',
    alert_type: 'chronicle-complaint',
    severity: 'warning',
    title: 'Chronicle Complaint Filed',
    message: 'A student-athlete disability accommodation complaint has been published by the Chronicle. Communications team should prepare a statement.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-016',
    is_read: false,
    is_emailed: true,
    created_at: '2026-03-22T08:30:00Z',
  },
  {
    id: 'alert-010',
    school_id: 'oregon',
    alert_type: 'coaching-change',
    severity: 'info',
    title: 'Coaching Departure',
    message: 'Men\'s soccer head coach departure after three seasons. Search committee formation recommended within 30 days.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-017',
    is_read: true,
    is_emailed: false,
    created_at: '2026-03-17T14:30:00Z',
  },
  {
    id: 'alert-011',
    school_id: 'oregon',
    alert_type: 'title-ix',
    severity: 'warning',
    title: 'Title IX Proportionality Gap Widening',
    message: 'Oregon\'s male-to-female athlete participation gap has increased to 8.3%, approaching the 10% threshold for review.',
    related_entity_type: null,
    related_entity_id: null,
    is_read: false,
    is_emailed: true,
    created_at: '2026-03-14T10:00:00Z',
  },
  {
    id: 'alert-012',
    school_id: 'oregon',
    alert_type: 'sentiment-drop',
    severity: 'info',
    title: 'Environmental Sentiment Dip',
    message: 'Coverage of facility environmental impact has generated a localized sentiment dip in sustainability-focused media. Overall score impact: -0.08.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-020',
    is_read: true,
    is_emailed: false,
    created_at: '2026-03-01T09:00:00Z',
  },

  // Duke (4 alerts)
  {
    id: 'alert-013',
    school_id: 'duke',
    alert_type: 'chronicle-complaint',
    severity: 'critical',
    title: 'Gender Pay Gap Report Published',
    message: 'The Chronicle has published a detailed report on coaching staff gender pay disparities at Duke. Immediate response recommended.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-023',
    is_read: false,
    is_emailed: true,
    created_at: '2026-03-21T10:30:00Z',
  },
  {
    id: 'alert-014',
    school_id: 'duke',
    alert_type: 'sentiment-drop',
    severity: 'warning',
    title: 'Arena Naming Controversy',
    message: 'Negative social media sentiment around the proposed arena name change reached -0.52. Monitoring escalation potential.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-028',
    is_read: true,
    is_emailed: false,
    created_at: '2026-02-21T09:00:00Z',
  },
  {
    id: 'alert-015',
    school_id: 'duke',
    alert_type: 'ncaa-violation',
    severity: 'info',
    title: 'Minor NCAA Violation',
    message: 'Level III improper benefits violation in men\'s tennis has been processed. Penalties are minimal and self-corrective measures accepted.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-026',
    is_read: true,
    is_emailed: false,
    created_at: '2026-03-06T09:30:00Z',
  },
  {
    id: 'alert-016',
    school_id: 'duke',
    alert_type: 'media-spike',
    severity: 'info',
    title: 'March Madness Media Surge',
    message: 'Duke basketball March Madness coverage has generated 1,200+ media mentions in 72 hours with 93% positive sentiment.',
    related_entity_type: null,
    related_entity_id: null,
    is_read: false,
    is_emailed: false,
    created_at: '2026-03-15T08:00:00Z',
  },

  // Kansas (4 alerts)
  {
    id: 'alert-017',
    school_id: 'kansas',
    alert_type: 'ncaa-violation',
    severity: 'critical',
    title: 'Level I NCAA Allegation',
    message: 'Kansas men\'s basketball has received a Level I allegation from NCAA enforcement. This is the highest severity tier. Legal response is mandatory within 90 days.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-031',
    is_read: false,
    is_emailed: true,
    created_at: '2026-03-19T14:30:00Z',
  },
  {
    id: 'alert-018',
    school_id: 'kansas',
    alert_type: 'chronicle-complaint',
    severity: 'critical',
    title: 'Whistleblower Fund Misuse Allegation',
    message: 'A whistleblower complaint alleging misuse of athletic department funds has been published. Audit committee activation recommended.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-030',
    is_read: false,
    is_emailed: true,
    created_at: '2026-03-23T08:30:00Z',
  },
  {
    id: 'alert-019',
    school_id: 'kansas',
    alert_type: 'sentiment-drop',
    severity: 'warning',
    title: 'Severe Sentiment Decline',
    message: 'Kansas overall sentiment score has dropped to 0.28, the lowest among tracked institutions. Multiple high-severity events are driving the decline.',
    related_entity_type: null,
    related_entity_id: null,
    is_read: false,
    is_emailed: true,
    created_at: '2026-03-25T07:00:00Z',
  },
  {
    id: 'alert-020',
    school_id: 'kansas',
    alert_type: 'media-spike',
    severity: 'info',
    title: 'Community Giving Coverage',
    message: 'Kansas basketball\'s $500K youth sports donation has been covered by 28 local and national outlets. Sentiment is highly positive.',
    related_entity_type: 'reputation_event',
    related_entity_id: 're-029',
    is_read: true,
    is_emailed: false,
    created_at: '2026-03-26T12:00:00Z',
  },
]

export const SEED_ALERT_THRESHOLDS: AlertThreshold[] = [
  {
    id: 'threshold-001',
    metric: 'Sentiment Score',
    threshold_value: 0.3,
    operator: 'lt',
    is_active: true,
    notify_email: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'threshold-002',
    metric: 'Media Mention Volume (24h)',
    threshold_value: 200,
    operator: 'gt',
    is_active: true,
    notify_email: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'threshold-003',
    metric: 'Title IX Proportionality Gap (%)',
    threshold_value: 10,
    operator: 'gte',
    is_active: true,
    notify_email: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'threshold-004',
    metric: 'Athletic Budget Ratio (%)',
    threshold_value: 15,
    operator: 'gt',
    is_active: false,
    notify_email: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'threshold-005',
    metric: 'Negative Event Count (30d)',
    threshold_value: 5,
    operator: 'gte',
    is_active: true,
    notify_email: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
]
