import { ReputationEvent } from '@/types/database'

export const SEED_REPUTATION_EVENTS: ReputationEvent[] = [
  // Michigan (7 events)
  {
    id: 're-001',
    school_id: 'michigan',
    event_type: 'media-mention',
    headline: 'Michigan Athletics Recognized for Academic Excellence Among Student-Athletes',
    source: 'ESPN',
    source_url: 'https://espn.com/example',
    sentiment_score: 0.82,
    severity: 'low',
    event_date: '2026-03-28T10:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-28T10:00:00Z',
  },
  {
    id: 're-002',
    school_id: 'michigan',
    event_type: 'social-sentiment',
    headline: 'Viral social media campaign boosts Michigan football recruiting visibility',
    source: 'Twitter/X Trends',
    source_url: null,
    sentiment_score: 0.65,
    severity: 'low',
    event_date: '2026-03-25T14:30:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-25T14:30:00Z',
  },
  {
    id: 're-003',
    school_id: 'michigan',
    event_type: 'chronicle-complaint',
    headline: 'Former athlete files Title IX complaint alleging unequal facility access',
    source: 'Chronicle of Higher Education',
    source_url: 'https://chronicle.com/example',
    sentiment_score: -0.71,
    severity: 'high',
    event_date: '2026-03-20T09:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-20T09:00:00Z',
  },
  {
    id: 're-004',
    school_id: 'michigan',
    event_type: 'ncaa-infraction',
    headline: 'Minor NCAA violation reported in men\'s basketball recruiting process',
    source: 'NCAA Enforcement',
    source_url: null,
    sentiment_score: -0.45,
    severity: 'medium',
    event_date: '2026-03-15T11:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-15T11:00:00Z',
  },
  {
    id: 're-005',
    school_id: 'michigan',
    event_type: 'coaching-change',
    headline: 'Michigan hires new women\'s volleyball head coach from Stanford',
    source: 'Michigan Athletics',
    source_url: 'https://mgoblue.com/example',
    sentiment_score: 0.55,
    severity: 'medium',
    event_date: '2026-03-10T16:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-10T16:00:00Z',
  },
  {
    id: 're-006',
    school_id: 'michigan',
    event_type: 'media-mention',
    headline: 'Investigation reveals concerns about booster influence on athletic department decisions',
    source: 'Detroit Free Press',
    source_url: 'https://freep.com/example',
    sentiment_score: -0.58,
    severity: 'high',
    event_date: '2026-03-05T08:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-05T08:00:00Z',
  },
  {
    id: 're-007',
    school_id: 'michigan',
    event_type: 'social-sentiment',
    headline: 'Community rallies behind Michigan swimmer\'s Olympic qualifier performance',
    source: 'Reddit/Social',
    source_url: null,
    sentiment_score: 0.91,
    severity: 'low',
    event_date: '2026-02-28T20:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-02-28T20:00:00Z',
  },

  // Alabama (7 events)
  {
    id: 're-008',
    school_id: 'alabama',
    event_type: 'media-mention',
    headline: 'Alabama football program praised for NIL compliance framework',
    source: 'Sports Illustrated',
    source_url: 'https://si.com/example',
    sentiment_score: 0.72,
    severity: 'low',
    event_date: '2026-03-29T12:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-29T12:00:00Z',
  },
  {
    id: 're-009',
    school_id: 'alabama',
    event_type: 'chronicle-complaint',
    headline: 'Faculty senate raises concerns about athletic budget growth outpacing academics',
    source: 'Chronicle of Higher Education',
    source_url: 'https://chronicle.com/example2',
    sentiment_score: -0.63,
    severity: 'high',
    event_date: '2026-03-24T09:30:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-24T09:30:00Z',
  },
  {
    id: 're-010',
    school_id: 'alabama',
    event_type: 'coaching-change',
    headline: 'Alabama announces new assistant coach for women\'s basketball program',
    source: 'Alabama Athletics',
    source_url: 'https://rolltide.com/example',
    sentiment_score: 0.40,
    severity: 'low',
    event_date: '2026-03-18T15:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-18T15:00:00Z',
  },
  {
    id: 're-011',
    school_id: 'alabama',
    event_type: 'ncaa-infraction',
    headline: 'NCAA opens preliminary inquiry into Alabama football practice hour violations',
    source: 'NCAA Enforcement',
    source_url: null,
    sentiment_score: -0.55,
    severity: 'high',
    event_date: '2026-03-12T10:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-12T10:00:00Z',
  },
  {
    id: 're-012',
    school_id: 'alabama',
    event_type: 'social-sentiment',
    headline: 'Fan backlash over proposed ticket price increase trends on social media',
    source: 'Twitter/X Trends',
    source_url: null,
    sentiment_score: -0.48,
    severity: 'medium',
    event_date: '2026-03-08T18:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-08T18:00:00Z',
  },
  {
    id: 're-013',
    school_id: 'alabama',
    event_type: 'media-mention',
    headline: 'Alabama gymnastics receives national attention for community outreach program',
    source: 'USA Today',
    source_url: 'https://usatoday.com/example',
    sentiment_score: 0.85,
    severity: 'low',
    event_date: '2026-03-02T11:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-02T11:00:00Z',
  },
  {
    id: 're-014',
    school_id: 'alabama',
    event_type: 'social-sentiment',
    headline: 'Positive sentiment surge following Alabama basketball\'s conference tournament run',
    source: 'Social Media Aggregate',
    source_url: null,
    sentiment_score: 0.78,
    severity: 'low',
    event_date: '2026-02-25T22:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-02-25T22:00:00Z',
  },

  // Oregon (7 events)
  {
    id: 're-015',
    school_id: 'oregon',
    event_type: 'media-mention',
    headline: 'Oregon track and field program featured in national sustainability initiative',
    source: 'The Athletic',
    source_url: 'https://theathletic.com/example',
    sentiment_score: 0.68,
    severity: 'low',
    event_date: '2026-03-30T09:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-30T09:00:00Z',
  },
  {
    id: 're-016',
    school_id: 'oregon',
    event_type: 'chronicle-complaint',
    headline: 'Student-athlete alleges academic support program failed to meet disability needs',
    source: 'Chronicle of Higher Education',
    source_url: 'https://chronicle.com/example3',
    sentiment_score: -0.60,
    severity: 'high',
    event_date: '2026-03-22T08:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-22T08:00:00Z',
  },
  {
    id: 're-017',
    school_id: 'oregon',
    event_type: 'coaching-change',
    headline: 'Oregon parts ways with men\'s soccer head coach after three seasons',
    source: 'Oregon Athletics',
    source_url: 'https://goducks.com/example',
    sentiment_score: -0.30,
    severity: 'medium',
    event_date: '2026-03-17T14:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-17T14:00:00Z',
  },
  {
    id: 're-018',
    school_id: 'oregon',
    event_type: 'social-sentiment',
    headline: 'Nike partnership renewal generates positive buzz among Oregon alumni',
    source: 'Instagram/Social',
    source_url: null,
    sentiment_score: 0.76,
    severity: 'low',
    event_date: '2026-03-13T16:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-13T16:00:00Z',
  },
  {
    id: 're-019',
    school_id: 'oregon',
    event_type: 'ncaa-infraction',
    headline: 'Self-reported secondary violation in Oregon softball recruiting communications',
    source: 'NCAA Enforcement',
    source_url: null,
    sentiment_score: -0.25,
    severity: 'low',
    event_date: '2026-03-07T10:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-07T10:00:00Z',
  },
  {
    id: 're-020',
    school_id: 'oregon',
    event_type: 'media-mention',
    headline: 'Oregon\'s new athletic facility criticized for environmental impact',
    source: 'Oregonian',
    source_url: 'https://oregonlive.com/example',
    sentiment_score: -0.42,
    severity: 'medium',
    event_date: '2026-03-01T07:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-01T07:00:00Z',
  },
  {
    id: 're-021',
    school_id: 'oregon',
    event_type: 'social-sentiment',
    headline: 'Oregon Ducks football spring game draws record social media engagement',
    source: 'Twitter/X Trends',
    source_url: null,
    sentiment_score: 0.88,
    severity: 'low',
    event_date: '2026-02-22T19:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-02-22T19:00:00Z',
  },

  // Duke (7 events)
  {
    id: 're-022',
    school_id: 'duke',
    event_type: 'media-mention',
    headline: 'Duke basketball\'s academic success rate tops conference for fifth consecutive year',
    source: 'CBS Sports',
    source_url: 'https://cbssports.com/example',
    sentiment_score: 0.90,
    severity: 'low',
    event_date: '2026-03-27T13:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-27T13:00:00Z',
  },
  {
    id: 're-023',
    school_id: 'duke',
    event_type: 'chronicle-complaint',
    headline: 'Report highlights gender pay gap between Duke men\'s and women\'s coaching staffs',
    source: 'Chronicle of Higher Education',
    source_url: 'https://chronicle.com/example4',
    sentiment_score: -0.68,
    severity: 'high',
    event_date: '2026-03-21T10:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-21T10:00:00Z',
  },
  {
    id: 're-024',
    school_id: 'duke',
    event_type: 'coaching-change',
    headline: 'Duke promotes from within for women\'s lacrosse head coaching position',
    source: 'Duke Athletics',
    source_url: 'https://goduke.com/example',
    sentiment_score: 0.50,
    severity: 'low',
    event_date: '2026-03-16T11:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-16T11:00:00Z',
  },
  {
    id: 're-025',
    school_id: 'duke',
    event_type: 'social-sentiment',
    headline: 'Duke March Madness run ignites record-high positive social media sentiment',
    source: 'Social Media Aggregate',
    source_url: null,
    sentiment_score: 0.93,
    severity: 'low',
    event_date: '2026-03-14T21:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-14T21:00:00Z',
  },
  {
    id: 're-026',
    school_id: 'duke',
    event_type: 'ncaa-infraction',
    headline: 'Duke men\'s tennis receives Level III violation for improper benefits',
    source: 'NCAA Enforcement',
    source_url: null,
    sentiment_score: -0.35,
    severity: 'medium',
    event_date: '2026-03-06T09:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-06T09:00:00Z',
  },
  {
    id: 're-027',
    school_id: 'duke',
    event_type: 'media-mention',
    headline: 'Duke student-athletes lead campus voter registration drive ahead of midterms',
    source: 'Durham Herald-Sun',
    source_url: 'https://heraldsun.com/example',
    sentiment_score: 0.75,
    severity: 'low',
    event_date: '2026-02-27T12:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-02-27T12:00:00Z',
  },
  {
    id: 're-028',
    school_id: 'duke',
    event_type: 'social-sentiment',
    headline: 'Negative reaction to proposed name change for Duke\'s basketball arena',
    source: 'Twitter/X Trends',
    source_url: null,
    sentiment_score: -0.52,
    severity: 'medium',
    event_date: '2026-02-20T17:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-02-20T17:00:00Z',
  },

  // Kansas (7 events)
  {
    id: 're-029',
    school_id: 'kansas',
    event_type: 'media-mention',
    headline: 'Kansas basketball program donates $500K to local youth sports initiatives',
    source: 'Kansas City Star',
    source_url: 'https://kansascity.com/example',
    sentiment_score: 0.88,
    severity: 'low',
    event_date: '2026-03-26T10:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-26T10:00:00Z',
  },
  {
    id: 're-030',
    school_id: 'kansas',
    event_type: 'chronicle-complaint',
    headline: 'Whistleblower alleges misuse of athletic department funds for non-sport travel',
    source: 'Chronicle of Higher Education',
    source_url: 'https://chronicle.com/example5',
    sentiment_score: -0.75,
    severity: 'critical',
    event_date: '2026-03-23T08:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-23T08:00:00Z',
  },
  {
    id: 're-031',
    school_id: 'kansas',
    event_type: 'ncaa-infraction',
    headline: 'Kansas men\'s basketball faces Level I allegation from NCAA enforcement',
    source: 'NCAA Enforcement',
    source_url: null,
    sentiment_score: -0.88,
    severity: 'critical',
    event_date: '2026-03-19T14:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-19T14:00:00Z',
  },
  {
    id: 're-032',
    school_id: 'kansas',
    event_type: 'coaching-change',
    headline: 'Kansas names new director of football operations from Big 12 rival',
    source: 'Kansas Athletics',
    source_url: 'https://kuathletics.com/example',
    sentiment_score: 0.35,
    severity: 'low',
    event_date: '2026-03-11T13:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-11T13:00:00Z',
  },
  {
    id: 're-033',
    school_id: 'kansas',
    event_type: 'social-sentiment',
    headline: 'Kansas fans express frustration over football season ticket waitlist system',
    source: 'Reddit/Social',
    source_url: null,
    sentiment_score: -0.40,
    severity: 'medium',
    event_date: '2026-03-04T19:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-03-04T19:00:00Z',
  },
  {
    id: 're-034',
    school_id: 'kansas',
    event_type: 'media-mention',
    headline: 'Kansas women\'s rowing achieves historic first at national championships',
    source: 'ESPN',
    source_url: 'https://espn.com/example2',
    sentiment_score: 0.80,
    severity: 'low',
    event_date: '2026-02-26T15:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-02-26T15:00:00Z',
  },
  {
    id: 're-035',
    school_id: 'kansas',
    event_type: 'social-sentiment',
    headline: 'Alumni celebrate Kansas basketball\'s Big 12 tournament championship victory',
    source: 'Social Media Aggregate',
    source_url: null,
    sentiment_score: 0.95,
    severity: 'low',
    event_date: '2026-02-18T23:00:00Z',
    details: null,
    ai_narrative: null,
    is_demo: true,
    created_at: '2026-02-18T23:00:00Z',
  },
]

export const SEED_SENTIMENT_TIMELINE = [
  // Michigan
  { school_id: 'michigan', date: '2025-10-01', score: 0.45, headline: 'Football season opener positive coverage' },
  { school_id: 'michigan', date: '2025-11-01', score: 0.38, headline: 'Mixed reviews after mid-season losses' },
  { school_id: 'michigan', date: '2025-12-01', score: 0.52, headline: 'Strong bowl game showing lifts sentiment' },
  { school_id: 'michigan', date: '2026-01-01', score: 0.30, headline: 'Offseason recruiting concerns emerge' },
  { school_id: 'michigan', date: '2026-02-01', score: 0.55, headline: 'Basketball surge boosts overall outlook' },
  { school_id: 'michigan', date: '2026-03-01', score: 0.42, headline: 'Title IX complaint tempers positive trend' },

  // Alabama
  { school_id: 'alabama', date: '2025-10-01', score: 0.70, headline: 'National championship expectations high' },
  { school_id: 'alabama', date: '2025-11-01', score: 0.55, headline: 'Upset loss lowers fan confidence' },
  { school_id: 'alabama', date: '2025-12-01', score: 0.48, headline: 'Playoff exclusion dampens mood' },
  { school_id: 'alabama', date: '2026-01-01', score: 0.35, headline: 'Coaching staff changes create uncertainty' },
  { school_id: 'alabama', date: '2026-02-01', score: 0.50, headline: 'Spring recruiting class lifts spirits' },
  { school_id: 'alabama', date: '2026-03-01', score: 0.60, headline: 'NIL compliance praise boosts reputation' },

  // Oregon
  { school_id: 'oregon', date: '2025-10-01', score: 0.60, headline: 'Big Ten transition draws attention' },
  { school_id: 'oregon', date: '2025-11-01', score: 0.65, headline: 'Competitive season sustains positivity' },
  { school_id: 'oregon', date: '2025-12-01', score: 0.58, headline: 'Facility expansion debate heats up' },
  { school_id: 'oregon', date: '2026-01-01', score: 0.50, headline: 'Environmental concerns surface' },
  { school_id: 'oregon', date: '2026-02-01', score: 0.72, headline: 'Nike partnership renewal boosts brand' },
  { school_id: 'oregon', date: '2026-03-01', score: 0.62, headline: 'Track program sustainability spotlight' },

  // Duke
  { school_id: 'duke', date: '2025-10-01', score: 0.55, headline: 'Basketball preseason hype builds' },
  { school_id: 'duke', date: '2025-11-01', score: 0.68, headline: 'Early season success drives enthusiasm' },
  { school_id: 'duke', date: '2025-12-01', score: 0.72, headline: 'Academic excellence recognition' },
  { school_id: 'duke', date: '2026-01-01', score: 0.60, headline: 'Conference play struggles briefly' },
  { school_id: 'duke', date: '2026-02-01', score: 0.45, headline: 'Arena naming controversy hits sentiment' },
  { school_id: 'duke', date: '2026-03-01', score: 0.80, headline: 'March Madness run electrifies fanbase' },

  // Kansas
  { school_id: 'kansas', date: '2025-10-01', score: 0.50, headline: 'Season outlook moderately positive' },
  { school_id: 'kansas', date: '2025-11-01', score: 0.42, headline: 'Football struggles weigh on mood' },
  { school_id: 'kansas', date: '2025-12-01', score: 0.55, headline: 'Basketball season opener lifts spirits' },
  { school_id: 'kansas', date: '2026-01-01', score: 0.35, headline: 'NCAA investigation concerns linger' },
  { school_id: 'kansas', date: '2026-02-01', score: 0.65, headline: 'Big 12 tournament success drives recovery' },
  { school_id: 'kansas', date: '2026-03-01', score: 0.28, headline: 'Whistleblower allegations hit hard' },
]

export const SEED_AI_NARRATIVES: Record<string, string> = {
  michigan:
    'The University of Michigan athletic department has experienced a mixed reputational landscape over the past quarter. Positive academic recognition for student-athletes and strong community engagement through the swimming program have been offset by a Title IX facility access complaint and a minor NCAA recruiting violation. Social media sentiment has been largely positive, driven by a viral recruiting campaign and Olympic qualifying performances. The recent investigative report on booster influence represents the most significant reputational risk, requiring proactive communications strategy. Overall sentiment trend: slightly positive with notable risk factors requiring monitoring.',
  alabama:
    'Alabama athletics maintains a generally strong reputation anchored by its football program brand, though several emerging challenges require attention. The NIL compliance framework has been praised nationally, positioning Alabama as a leader in the evolving landscape. However, faculty concerns about budget prioritization and an NCAA inquiry into practice hour violations present significant headwinds. The gymnastics community outreach program has generated exceptionally positive coverage. Fan sentiment showed temporary decline over ticket pricing but recovered substantially during the basketball conference tournament. Overall sentiment trend: moderately positive with institutional tension points.',
  oregon:
    'Oregon athletics benefits from strong brand partnerships and competitive athletic programs, driving generally positive public perception. The Nike partnership renewal and spring game social media engagement represent high points for the brand. Environmental criticisms of the new athletic facility and a disability accommodation complaint in academic support present reputational challenges that align with broader institutional values discussions. The coaching change in men\'s soccer was handled cleanly with minimal negative impact. The track and field sustainability initiative aligns well with Oregon\'s institutional identity. Overall sentiment trend: positive with environmental and equity considerations.',
  duke:
    'Duke University\'s athletic reputation remains exceptionally strong, driven primarily by basketball excellence both on the court and in academics. The program\'s fifth consecutive year leading conference academic success rates reinforces the student-athlete development narrative. The March Madness run generated the highest positive social media sentiment of any school in the dataset. Challenges include a gender pay gap report for coaching staffs and a minor NCAA tennis violation. The arena naming controversy briefly dampened social sentiment but was overshadowed by tournament success. Student-athlete civic engagement has generated additional positive coverage. Overall sentiment trend: strongly positive with gender equity concerns.',
  kansas:
    'Kansas athletics faces the most challenging reputational environment among tracked institutions. While basketball success at the Big 12 tournament and community giving initiatives have generated strong positive sentiment, the Level I NCAA allegation and whistleblower complaint about fund misuse represent severe reputational threats. These high-severity events have created significant negative media cycles that offset the positive coverage. Fan frustration over the ticket waitlist system adds minor consumer dissatisfaction to the narrative. The football operations hire was a neutral event. Immediate crisis communications and institutional response are recommended. Overall sentiment trend: negative due to high-severity compliance issues.',
}
