export const SCHOOLS = [
  {
    slug: 'michigan',
    name: 'University of Michigan',
    shortName: 'Michigan',
    conference: 'Big Ten',
    mascot: 'Wolverines',
    primaryColor: '#00274C',
    secondaryColor: '#FFCB05',
    state: 'MI',
    enrollment: 47907,
  },
  {
    slug: 'alabama',
    name: 'University of Alabama',
    shortName: 'Alabama',
    conference: 'SEC',
    mascot: 'Crimson Tide',
    primaryColor: '#9E1B32',
    secondaryColor: '#828A8F',
    state: 'AL',
    enrollment: 38320,
  },
  {
    slug: 'oregon',
    name: 'University of Oregon',
    shortName: 'Oregon',
    conference: 'Big Ten',
    mascot: 'Ducks',
    primaryColor: '#154733',
    secondaryColor: '#FEE123',
    state: 'OR',
    enrollment: 23634,
  },
  {
    slug: 'duke',
    name: 'Duke University',
    shortName: 'Duke',
    conference: 'ACC',
    mascot: 'Blue Devils',
    primaryColor: '#003087',
    secondaryColor: '#FFFFFF',
    state: 'NC',
    enrollment: 16606,
  },
  {
    slug: 'kansas',
    name: 'University of Kansas',
    shortName: 'Kansas',
    conference: 'Big 12',
    mascot: 'Jayhawks',
    primaryColor: '#0051BA',
    secondaryColor: '#E8000D',
    state: 'KS',
    enrollment: 27638,
  },
] as const

export type SchoolSlug = (typeof SCHOOLS)[number]['slug']
